name: PoscBox
version: '1.0-INDEV'
main: me.lord.poscbox.PoscBox
api-version: 1.19
depend: [ FastAsyncWorldEdit ]
authors: [ thelordman, hotpocket184, TotallyAl, liamint ]
description: The main plugin for the PoscBox Minecraft server
website: https://discord.gg/YeUacKAWV2
commands:
  gmc:
    description: Changes your or an online player's gamemode to creative.
    usage: /gmc [<player>]
  gms:
    description: Changes your or an online player's gamemode to survival.
    usage: /gms [<player>]
  gma:
    description: Changes your or an online player's gamemode to adventure.
    usage: /gma [<player>]
  gmsp:
    description: Changes your or an online player's gamemode to spectator.
    usage: /gmsp [<player>]
  shop:
    description: Opens the wool shop.
    usage: /shop
  joinkit:
    description: Give the Join Kit to a player.
    usage: /joinkit [<player>]
  economy:
    description: Modify the server economy.
    aliases:
      - eco
    usage: /economy <player> [<text>] [<amount>]
  rank:
    description: Modify ranks of players.
    usage: /rank <player> <set> <rank>