name: poscbox
version: '${version}'
main: me.lord.poscbox.PoscBox
api-version: 1.19
depend: [ FastAsyncWorldEdit ]
authors: [ thelordman ]
description: The main plugin for the PoscBox Minecraft server
website: http://www.posc.store
commands:
  gmc:
    description: Changes your or an online player's gamemode to creative.
    usage: /gmc [<player>]
  gms:
    description: Changes your or an online player's gamemode to survival.
    usage: /gms [<player>]
  gma:
    description: Changes your or an online player's gamemode to adventure.
    usage: /gma [<player>]
  gmsp:
    description: Changes your or an online player's gamemode to spectator.
    usage: /gmsp [<player>]
