name: PoscBox
version: '1.0-INDEV'
main: me.lord.poscbox.PoscBox
api-version: 1.19
depend: [ FastAsyncWorldEdit ]
authors: [ thelordman, hotpocket184, TotallyAl, liamint ]
description: The main plugin for the PoscBox Minecraft server
website: https://discord.gg/YeUacKAWV2
commands:
  gmc:
    description: Changes your or an online player's gamemode to creative.
    usage: /gmc [<player>]
  gms:
    description: Changes your or an online player's gamemode to survival.
    usage: /gms [<player>]
  gma:
    description: Changes your or an online player's gamemode to adventure.
    usage: /gma [<player>]
  gmsp:
    description: Changes your or an online player's gamemode to spectator.
    usage: /gmsp [<player>]
  shop:
    description: Opens the wool shop.
    usage: /shop
  joinkit:
    description: Give the Join Kit to a player.
    usage: /joinkit [<player>]
  economy:
    description: Modify the server economy.
    aliases:
      - eco
    usage: /economy <player> [<text>] [<amount>]
  rank:
    description: Modify ranks of players.
    usage: /rank <player> <set> <rank>
  punishments:
    description: Shows you the punishment history of an offline player or yourself.
    usage: /punishments [player]
  mute:
    description: Mute a player.
    usage: /mute <player> [time | perm] [reason] [-s]
  unmute:
    description: Unmute a player.
    usage: /unmute <player> [-s]
  kick:
    description: Kick a player.
    usage: /kick <player> [reason] [-s]
  warn:
    description: Warn a player.
    usage: /warn <player> [reason] [-s]
  ban:
    description: Ban a player.
    usage: /ban <player> [time | perm] [reason] [-s]
  unban:
    description: Ban a player.
    usage: /unban <player> [-s]
  ipban:
    description: Ban the IP address of a player.
    aliases: banip
    usage: /ipban <player> [time | perm] [reason] [-s]
  unipban:
    description: Unban the IP address of a player.
    aliases: unbanip
    usage: /unipban <player> [-s]